### ISSUE TITLE
Roadmap to first public beta release

### ISSUE THREAD

**Issue by sebirdman** [diefarbe/bunte-farben#1]
### General

- [ ] Works on mac/windows/linux
- [ ] Uses rest api to make changes

### ui

- [ ] Can edit any key to any color
- [ ] Access to timing controls
- [ ] can quickly copy and paste edits from one key to another (multiple key editing)
- [ ] can dump out some kind of "configuration" for saving a profile and sharing it with others (config should be json that corresponds to rest-api)
